
CREATE TABLE IF NOT EXISTS InstanceDescription (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL DEFAULT '',
    Description TEXT NOT NULL DEFAULT '',
    Purpose TEXT NOT NULL DEFAULT '',
    ContactInfo TEXT NOT NULL DEFAULT '',
    IsEnabled  BOOLEAN NOT NULL DEFAULT 0,
    CustomLandingPageHtml TEXT NOT NULL DEFAULT '',
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
